name: BasicReversiGame
description: A Reversi game built in Flutter.
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  async: 2.0.8
  flutter:
    sdk: flutter
  flutter_inapp_purchase: 0.8.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          style: italic
